url: http://readygraph.com


# Site settings
title: ReadyGraph
email: hello@readygraph.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 093E7D
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/readygraph
  - title: facebook
    url: https://www.facebook.com/pages/Readygraph/538382472935319
  - title: google-plus
    url: https://plus.google.com/107911777724541494367/posts 

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty